### ISSUE TITLE
Date Range on Search and Filters

### ISSUE THREAD

**Issue by safchow** [uwblueprint/supportive-housing#140]
user should be able to only fill out one of the fields (for example, only a start date and all log records from that start date will display). Also, display an error toast message if the user selects an invalid date range (i.e. end date < start date)

**Comment by owen-sellner** [comment]
I think this is really similar to what I did for this PR (https://github.com/uwblueprint/supportive-housing/pull/163)

**Comment by helenellyx** [comment]
need (#163) to be merged in first, but I have other changes on my branch, so when 163 gets merged, just ping me and I will push my branch 🙌
