### ISSUE TITLE
Integrate Duo2FA

### ISSUE THREAD

**Issue by DinuWije** [uwblueprint/supportive-housing#19]
## Summary
- Relief staff should only be able to login when they are on-site in the housing building
- The housing building has a single desktop that the relief staff use to make the logs
- The idea to implement the login restriction is to have Duo2FA installed on the desktop, and require that all relief staff enter a code from the app before they can login. 
- Not sure if this is the best approach though, so this task needs some more investigation
- 5 point estimation
## Goals
- [ ] Figure out the best way to implement location based login restrictions (if its not Duo)
- [ ] Figure out if Duo has a native application that can be downloaded and used to generate codes on a computer
- [ ] If Duo is the best option, figure out pricing, API use, and Duo for desktop
- [ ] If Duo is the best option, integrate it with our sign-in flow for Relief Staff
## Implementation
- Start by investigating options to solve the location-based sign-on problem
- For Duo, take a look at the options available and play around with Duo Desktop
- If Duo is suited for our use case, use the Duo API to integrate 2fa auth for the Relief Staff role (check if Duo integrates with Firebase)
## Notes
- This is an investigation heavy task but could be very interesting to develop end-to-end

**Comment by connor-bechthold** [comment]
### Investigation Results

Pricing with this strategy should be free/very minimal.  From what I've seen, the plans are user based, where a user belongs to an application. In our case, we would just need to create one user for the application, and all 2FA requests would go under that user and can be subsequently verified at the remote location.

The main blocker with Duo is that 2FA verification can only be done through a mobile device such as a cellphone. We only have access to a desktop, so unless there was a shared phone available, this solution isn't really viable.

The other alternative is to use [Authy by Twilio](https://authy.com/guides/twilio/). This was the most secure/convenient application that allows us to perform 2FA on a desktop application. We can create our application in the Twilio console, and then create a single user that all users can verify under, which allows us to stay in the free plan. 

The interface looks like this:

![Screen Shot 2023-02-01 at 6 34 02 PM](https://user-images.githubusercontent.com/64047863/216191868-8f777507-75ce-4bb1-90fe-8abfc4bd25c5.png)
![Screen Shot 2023-02-01 at 6 34 09 PM](https://user-images.githubusercontent.com/64047863/216191872-134e203c-da40-4ab8-8a24-48693a348816.png)

The implementation of this would be super straightforward:
- User signs in and is brought to a page where they would need to enter the code from the Authy app
- That code can be passed through to the Authy API along with the ID of the user created, and the API will send back a response saying if the code is correct

Possible drawbacks:
- Users have to enter a 6 digit code in 20 seconds before the code refreshes, which could possibly get annoying if they're not fast enough
- The API we would need to use is being deprecated. The updated API is in pilot, so we shouldn't use that yet. Twilio does explicitly mention that they aren't discontinuing the Authy app anytime soon, so the support should still be sufficient for our case
![Screen Shot 2023-02-01 at 6 41 54 PM](https://user-images.githubusercontent.com/64047863/216192874-12f507f8-c955-4044-a2b9-4794bdfef477.png)
