### ISSUE TITLE
Implement Design System

### ISSUE THREAD

**Issue by juthikahoque** [uwblueprint/supportive-housing#64]
## Summary
Current we use Chakra UI for our frontend components. We want to customize different components (i.e. tags, input boxes, buttons, typography, etc.) to fit our design system (https://www.figma.com/file/Gs2ZhbdvW8aLsXDmFO6rky/SHOW-Design-System?node-id=40-2438&t=tVmWJZNEhAzbyxWp-0).

## Goals
- [ ] Customized components so that we don't need to apply designs everywhere

## Implementation
Instead of doing this in CSS, we can customize Chakra's components based on different tags (you can see CAS's implementation of their design system as an example).

**Comment by safchow** [comment]
some docs to refer to when starting: https://chakra-ui.com/docs/styled-system/component-style
